---
version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/svc-base/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - /env/default
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "clickhouse/clickhouse-server"
      - dependency-name: "fluent/fluent-bit"
      - dependency-name: "redis"
      - dependency-name: "scality/backbeat"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "scality/cloudserver"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
    groups:
      workbench:
        patterns:
          - "*"
        update-types:
          - patch
