global:
  log_level: info

features:
  access_logging:
    enabled: true
  s3_frontend:
    enabled: true
  lifecycle:
    enabled: true

cloudserver:
  image: ghcr.io/scality/cloudserver:9.3.6

vault:
  image: ghcr.io/scality/vault:7.86.0

backbeat:
  image: ghcr.io/scality/backbeat:9.0.25-federation

s3_metadata:
  image: ghcr.io/scality/metadata:9.9.0-standalone

clickhouse:
  image: clickhouse/clickhouse-server:24.3.2.23-alpine

fluentbit:
  image: fluent/fluent-bit:3.0.2

nginx:
  image: nginx:1.27-alpine

redis:
  image: redis:8.4.0-alpine
