global:
  log_level: info

features:
  access_logging:
    enabled: true
  s3_frontend:
    enabled: true
  lifecycle:
    enabled: true
  cross_region_replication:
    enabled: true

cloudserver:
  image: ghcr.io/scality/cloudserver:9.3.19

vault:
  image: ghcr.io/scality/vault:7.93.0

backbeat:
  image: ghcr.io/scality/backbeat:9.3.7-federation

s3_metadata:
  image: ghcr.io/scality/metadata:9.16.0-standalone

clickhouse:
  image: clickhouse/clickhouse-server:24.3.2.23-alpine

fluentbit:
  image: cr.fluentbit.io/fluent/fluent-bit:4.2.3.1

nginx:
  image: nginx:1.27-alpine

redis:
  image: redis:8.4.0-alpine
