global:
  log_level: info

features:
  access_logging:
    enabled: true
  s3_frontend:
    enabled: true

cloudserver:
  image: ghcr.io/scality/cloudserver:61a3b01b8545d23dd98e88d36c64cfb198f25f65

vault:
  image: ghcr.io/scality/vault:7.85.0

s3_metadata:
  image: ghcr.io/scality/metadata:9.9.0-standalone

clickhouse:
  image: clickhouse/clickhouse-server:24.3.2.23-alpine

fluentbit:
  image: fluent/fluent-bit:3.0.2

nginx:
  image: nginx:1.27-alpine
